name: Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: myflix-videocatalog

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest --push .

      - name: Extract IP from SERVER_SECRET
        id: extract-ip
        run: echo "::set-output name=ip::$(echo ${{ secrets.SERVER_SECRET }} | cut -d@ -f2)"

      - name: Create ~/.ssh directory
        run: mkdir -p ~/.ssh

      - name: Add SSH key to known_hosts
        run: ssh-keyscan -H ${{ steps.extract-ip.outputs.ip }} >> ~/.ssh/known_hosts

      - name: Update Docker Swarm Service
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem ${{ secrets.SERVER_SECRET }} "docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.REPO_NAME }}:latest myflix_${{ env.REPO_NAME }}"